universe = docker
docker_image = gjoschka/massspec_with_wandb
executable = train.sh
output = qm9_diff.$(ClusterId).$(ProcId).out
error = qm9_diff.$(ClusterId).$(ProcId).err
log = qm9_diff.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 32
request_memory = 32G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
